# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='heritage',
        ),
        migrations.AddField(
            model_name='heritage',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
    ]
