# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heritage',
            name='update_date',
        ),
    ]
