# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 20:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritage',
            name='event_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 13, 23, 11, 24, 542823), null=True),
        ),
    ]
