# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171213_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritage',
            name='event_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 14, 14, 20, 17, 69464), null=True),
        ),
    ]
