# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171108_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heritage',
            old_name='tags',
            new_name='tag',
        ),
    ]
