# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20171119_1734'),
        ('api', '0003_merge_20171118_2135'),
    ]

    operations = [
    ]
