# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='username2',
            field=models.CharField(default='username', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo_path',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
