# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171108_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heritage',
            old_name='tag',
            new_name='tags',
        ),
    ]
