# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171109_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heritage',
            old_name='tags',
            new_name='tag',
        ),
    ]
