# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 08:23
from __future__ import unicode_literals

import api.model.media
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20171122_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='data_path',
        ),
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(default='Images/no_image.jpg', upload_to=api.model.media.user_directory_path),
        ),
        migrations.AlterField(
            model_name='media',
            name='heritage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='api.Heritage'),
        ),
    ]
