# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171102_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username2',
            new_name='username',
        ),
    ]
