# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171109_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heritage',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
