# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
