runserver:
	sudo nohup python bounswe2017group1/web/manage.py runserver 0.0.0.0:3000 &

quitserver:
	sudo pkill python
	sudo pkill nohup

viewlog:
	sudo cat nohup.out

watchserver:
	sudo python bounswe2017group1/web/manage.py runserver 0.0.0.0:3000 

